### ISSUE TITLE
Zigate is_initialized=False

### ISSUE THREAD

**Issue by bckthomas** [zigpy/zigpy-zigate#102]
Hello
I have a zigate v1 with the last firmware version (3.2 legacy)
In Home Assistant (2021.10.0) logs, I have this log message : Device is partially initialized: ZiGateDevice model='ZiGate USB-TTL 3.20' manuf='ZiGate' nwk=0x0000 ieee=00:15:8d:00:01:ed:a6:32 is_initialized=False

How can I fix this ?
Thanks

**Comment by puddly** [comment]
@Hedda I think the proper fix is https://github.com/puddly/zigpy-zigate/commit/88d1cb6f3400a2a64966b410deb0cb6dbd65c6a6#commitcomment-58038993. I don't have the hardware to test.
