### ISSUE TITLE
Zlinky intégration

### ISSUE THREAD

**Issue by max5962** [zigpy/zigpy-zigate#103]
Hello, 
I just install my zlinky, it's bind but not seems to work.
Any one to make it working ?
Thanks

**Comment by Hedda** [comment]
Probably not an issue in zigpy/zigpy-zigate however need a quirk in zha-device-handlers so see -> https://github.com/zigpy/zha-device-handlers/issues/1146

ZHA integration docs explai why here -> https://www.home-assistant.io/integrations/zha#zha-exception-and-deviation-handling

**Comment by pipiche38** [comment]
That is not a zigpy-zigate issue but much more a ZHA/Quirks issue

**Comment by max5962** [comment]
indeed. i close the issue
