### ISSUE TITLE
how to access Zigate specific functions

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zigpy-zigate#108]
This is more a Zigpy question rather than a zigpy-zigate one,

In a Zigpy integration, how can from application level I get access to Zigate specific request ?

For example setting the 

- Zigate into debug mode ? ( command 0x0001 )
- Getting the list of active node ? ( command 0x0015 )

and few others like is the device in permit mode  ...

**Comment by Hedda** [comment]
It probably better to post zigpy questions to https://github.com/zigpy/zigpy/issues (especially now that there is no active maintainer of zigpy-zigate)
