### ISSUE TITLE
RPi.GPIO dependency is no more installed in Home Assistant Core 2022.7.7

### ISSUE THREAD

**Issue by stephane** [zigpy/zigpy-zigate#124]
The issue is described here https://github.com/home-assistant/core/issues/75755

My workaround:
- log into the docker VM with `docker exec -it <sha1> bash`
- `apk add build-base`
- `pip install RPi.GPIO`

**Comment by puddly** [comment]
We've migrated to [gpiozero](https://gpiozero.readthedocs.io/en/stable/) to work around this problem.

**Comment by stephane** [comment]
I didn't had this issue in latest HA updates so I think your fix is effective (#125).
Thank you @puddly
