### ISSUE TITLE
Confirm compability with new Third Reality Zigbee Coordinator USB Dongle based on Buffalo Lab BL706 radio SoC and ZiGate firmware?

### ISSUE THREAD

**Issue by Hedda** [zigpy/zigpy-zigate#154]
Anyone tested ThirdReality's Zigbee Coordinator USB-C adapter with zigpy + zigpy-zigate via Home Assistant's ZHA integration?

https://3reality.com/product/3-0-usbc-dongle/

https://www.amazon.com/live/video/029a0aca47284ae99ba48cc9efd118c3?ref_=dp_vse_rvc_3

https://github.com/thirdreality/ThiredReality-Zigbee-3.0-USB-dongle

https://manuals.plus/third-reality/zigbee-usbc-dongle-adapter-manual

Interesting that have not heard about this Zigbee Coordinator adapter previously considering that Third Reality (3reality/3R) is a member of the Nabu Casa / Home Assistant's Works with Home Assistant partner program for their other Zigbee device products. 

https://www.home-assistant.io/integrations/third_reality/

Apparently it is based on Buffalo Lab BL706 radio SoC and ZiGate firmware and it sais it should work with ZHA (via zigpy-zigate)? 

For reference; Zigbee2MQTT's zigbee-herdsman developers have identified some issues with Buffalo's specific handling of ZCL:

* https://github.com/Koenkk/zigbee-herdsman/issues/1037
  * https://github.com/Koenkk/zigbee-herdsman/pull/1033

![image](https://github.com/zigpy/zigpy-zigate/assets/6320001/08275d18-bde3-4459-b657-23772af6e6a5)

It is already globally available and being sold on Amazon and some other sites worldwide:

* https://www.amazon.com/THIRDREALITY-USBC-Dongle-Universal-Compatible-Zigbee2Mqtt/dp/B0C9D56QJ4 (USA)
* https://www.amazon.de/-/en/THIRDREALITY-Universal-Compatible-Assistant-Zigbee2Mqtt/dp/B0CHB22GMC/ (European Union)
* https://www.amazon.co.uk/THIRDREALITY-USBC-Dongle-Universal-Compatible-Zigbee2Mqtt/dp/B0CHB22GMC (Great Britan)
* https://auspowers.com/products/thirdreality-zigbee-3-0-usbc-dongle-universal-zigbee-usb-stick-compatible-with-home-assistant-zha-and-zigbee2mqtt?variant=42346570219700 (Australia)
* https://www.ubuy.com.ps/en/product/F97QVD6D2-thirdreality-zigbee-3-0-usbc-dongle-universal-zigbee-usb-stick-compatible-with-home-assistant-zha-and-zigbee2mqtt (Middle East)

Can only find reports that several people says it is working fine in Zigbee2MQTT (Z2M) when selecting zigate as radio adapter type.

![image](https://github.com/zigpy/zigpy-zigate/assets/6320001/226726b3-1d8a-4e12-8a07-c87ae63e76f6)

![image](https://github.com/zigpy/zigpy-zigate/assets/6320001/7770054f-c411-4331-be6b-3adb605aa051)

![image](https://github.com/zigpy/zigpy-zigate/assets/6320001/09be0f11-991d-45ac-98eb-7f08b3c316c1)

![image](https://github.com/zigpy/zigpy-zigate/assets/6320001/7594e28e-c748-4fbf-8cc2-5198cbe22128)

**Comment by puddly** [comment]
It is not compatible. The ZiGate protocol is deprecated.
