### ISSUE TITLE
implement an `api.probe()` method

### ISSUE THREAD

**Issue by Adminiuga** [zigpy/zigpy-zigate#21]
Whenever you have a chance, could you implement something similar to https://github.com/zigpy/zigpy-deconz/pull/101 ?

Essentially I'd like to be able to run `await zigpy_zigate.api.ZiGate.probe(serial_port_path, baudrate)` and get either a `True` if radio was detected or `False` otherwise. Method should swallow all exceptions. 
Currently for deconz or EZSP it justs opens the port, issues some command to which it always should get a response and closes the port.

Not sure if anything similar is possible with zigate.  Maybe issuing `set_raw_command()` and if successful then consider the radio is there.

**Comment by Hedda** [comment]
@doudz Also see similar https://github.com/zigpy/zigpy-cc/pull/35
