### ISSUE TITLE
Not able to include my valve

### ISSUE THREAD

**Issue by BornTKill** [zigpy/zigpy-zigate#37]
Dear,

I was able to include my zigbee valve (_TYZB01_ymcdbl3u TS0111) with this project https://github.com/doudz/homeassistant-zigate but not with ZHA Integration in HA.

Each time I try to add the device I receive ;
XX:XX:XX:XX:XX has left the Network.

Any ideas ?
Also can you tell me how to enable debug log ?

For you information my 5 Aqara sensors have been added and my Honeywell Gas Detector also.

Thank You.

**Comment by Gamester17** [comment]
See troubleshooting section in https://www.home-assistant.io/integrations/zha/ for how to enable debug logs for ZHA in HA.

More details on debug logs and bug reporting is also available in https://github.com/zigpy/zigpy/blob/dev/CONTRIBUTING.md

**Comment by Hedda** [comment]
@BornTKill Did you manage to fix this and if so are you OK to close this yourself as resolved or will you keep it open?

**Comment by BornTKill** [comment]
@Hedda I didn’t test yet. I will reopen if need

**Comment by Hedda** [comment]
Suggest that you then Home Assistant 0.114 or 0.115 when it is released (beta now but the release is planned for 17 September)

https://rc.home-assistant.io/blog/2020/09/07/release-115/

If it still does not work then should follow troubleshooting steps in -> in https://www.home-assistant.io/integrations/zha/

**Comment by BornTKill** [comment]
Ok !
