### ISSUE TITLE
Database is not created and all devices are lost after restart

### ISSUE THREAD

**Issue by pipiche38** [zigpy/zigpy-zigate#41]
When running the library (branch master), I'm able to provision new devices, but when restarting all devices seems to be lost.

I'm using the following APP Config and calling ControllerApplication() in that way 

```
APP_CONFIG = {
    config.CONF_DEVICE: {
        config.CONF_DEVICE_PATH: "/dev/ttyUSBRPI3",
    },
    config.CONF_DATABASE: "/var/lib/domoticz/plugins/Domoticz-Zigpy/Datas/zigpy.db",
}

zigpyApp = ControllerApplication(APP_CONFIG)
```

Don't know if this is related to : https://github.com/zigpy/zigpy/issues/207

**Comment by doudz** [comment]
I think you should open an issue on zigpy , I don't think it's related to zigate radio
