### ISSUE TITLE
PiZiGate + TS0601

### ISSUE THREAD

**Issue by Kalypox** [zigpy/zigpy-zigate#67]
Hello,
I bought a Tuya thermostatic valve (TS0601) and I would like to pair it with my Pizigate, but it doesn't work very well...
The pair is ok, but i can't read anything, and ZigPy doesn't create any entity.

I put the verbose mode, this is the log :
http://pastebin.fr/73875

This is my "ZigBee informations" :
http://pastebin.fr/73877

I'll also search, I'll keep you informed.

Thanks !

**Comment by doudz** [comment]
I don't think the problem is related to zigate itself
you should open an issue on zigpy, https://github.com/zigpy/zigpy/issues
